services:
    CurlUrl:
        class: Pages\PagesBundle\Services\CurlUrl
        
    validator.check.url:
        class: Pages\PagesBundle\Validator\Constraints\constraintsCheckUrlValidator
        arguments: [@CurlUrl]
        tags:
            - { name: validator.constraint_validator, alias: validatorCheckUrl }
