villes:
    pattern: /villes/{cp}
    defaults: {_controller: UtilisateursBundle:Utilisateurs:villes}
    options:
        expose: true

factures:
    pattern: /profile/factures
    defaults: {_controller: UtilisateursBundle:Utilisateurs:factures}
    
facturesPDF:
    pattern: /profile/factures/pdf/{id}
    defaults: {_controller: UtilisateursBundle:Utilisateurs:facturesPDF}   
