<?php

namespace Pages\PagesBundle\Repository;

/**
 * PagesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PagesRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByRemove() 
    {
        $qb = $this->createQueryBuilder('u')
                ->select('u')
                ->where('u.deletedAt IS NOT NULL');
        
        return $qb->getQuery()->getResult();
    }
}
